import type { Config } from "tailwindcss";

export default {
    content: [
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card) / <alpha-value>)",
                    foreground: "hsl(var(--card-foreground) / <alpha-value>)",
                },

                // Material Design 3 (M3) Surface & Container Colors with Alpha Channel Support
                "surface": "hsl(var(--md-sys-color-surface) / <alpha-value>)",
                "on-surface": "hsl(var(--md-sys-color-on-surface) / <alpha-value>)",
                "on-surface-variant": "hsl(var(--md-sys-color-on-surface-variant) / <alpha-value>)",
                "outline": "hsl(var(--md-sys-color-outline) / <alpha-value>)",
                "outline-variant": "hsl(var(--md-sys-color-outline-variant) / <alpha-value>)",
                "surface-container-lowest": "hsl(var(--md-sys-color-surface-container-lowest) / <alpha-value>)",
                "surface-container-low": "hsl(var(--md-sys-color-surface-container-low) / <alpha-value>)",
                "surface-container": "hsl(var(--md-sys-color-surface-container) / <alpha-value>)",
                "surface-container-high": "hsl(var(--md-sys-color-surface-container-high) / <alpha-value>)",
                "surface-container-highest": "hsl(var(--md-sys-color-surface-container-highest) / <alpha-value>)",
                "primary-container": "hsl(var(--md-sys-color-primary-container) / <alpha-value>)",
                "on-primary-container": "hsl(var(--md-sys-color-on-primary-container) / <alpha-value>)",
                "secondary-container": "hsl(var(--md-sys-color-secondary-container) / <alpha-value>)",
                "on-secondary-container": "hsl(var(--md-sys-color-on-secondary-container) / <alpha-value>)",
                "tertiary-container": "hsl(var(--md-sys-color-tertiary-container) / <alpha-value>)",
                "on-tertiary-container": "hsl(var(--md-sys-color-on-tertiary-container) / <alpha-value>)",
                "error-container": "hsl(var(--md-sys-color-error-container) / <alpha-value>)",
                "on-error-container": "hsl(var(--md-sys-color-on-error-container) / <alpha-value>)",
                "success-container": "hsl(var(--md-sys-color-success-container) / <alpha-value>)",
                "on-success-container": "hsl(var(--md-sys-color-on-success-container) / <alpha-value>)",

                // Explicit Material Design 3 semantic aliases
                "m3-primary": "hsl(var(--md-sys-color-primary) / <alpha-value>)",
                "m3-on-primary": "hsl(var(--md-sys-color-on-primary) / <alpha-value>)",
                "m3-primary-container": "hsl(var(--md-sys-color-primary-container) / <alpha-value>)",
                "m3-on-primary-container": "hsl(var(--md-sys-color-on-primary-container) / <alpha-value>)",
                "m3-secondary": "hsl(var(--md-sys-color-secondary) / <alpha-value>)",
                "m3-on-secondary": "hsl(var(--md-sys-color-on-secondary) / <alpha-value>)",
                "m3-secondary-container": "hsl(var(--md-sys-color-secondary-container) / <alpha-value>)",
                "m3-on-secondary-container": "hsl(var(--md-sys-color-on-secondary-container) / <alpha-value>)",
                "m3-tertiary": "hsl(var(--md-sys-color-tertiary) / <alpha-value>)",
                "m3-on-tertiary": "hsl(var(--md-sys-color-on-tertiary) / <alpha-value>)",
                "m3-tertiary-container": "hsl(var(--md-sys-color-tertiary-container) / <alpha-value>)",
                "m3-on-tertiary-container": "hsl(var(--md-sys-color-on-tertiary-container) / <alpha-value>)",
                "m3-error": "hsl(var(--md-sys-color-error) / <alpha-value>)",
                "m3-on-error": "hsl(var(--md-sys-color-on-error) / <alpha-value>)",
                "m3-error-container": "hsl(var(--md-sys-color-error-container) / <alpha-value>)",
                "m3-on-error-container": "hsl(var(--md-sys-color-on-error-container) / <alpha-value>)",
                "m3-success": "hsl(var(--md-sys-color-success) / <alpha-value>)",
                "m3-on-success": "hsl(var(--md-sys-color-on-success) / <alpha-value>)",
                "m3-success-container": "hsl(var(--md-sys-color-success-container) / <alpha-value>)",
                "m3-on-success-container": "hsl(var(--md-sys-color-on-success-container) / <alpha-value>)",
                "m3-surface": "hsl(var(--md-sys-color-surface) / <alpha-value>)",
                "m3-on-surface": "hsl(var(--md-sys-color-on-surface) / <alpha-value>)",
                "m3-on-surface-variant": "hsl(var(--md-sys-color-on-surface-variant) / <alpha-value>)",
                "m3-outline": "hsl(var(--md-sys-color-outline) / <alpha-value>)",
                "m3-outline-variant": "hsl(var(--md-sys-color-outline-variant) / <alpha-value>)",
                "m3-surface-container-lowest": "hsl(var(--md-sys-color-surface-container-lowest) / <alpha-value>)",
                "m3-surface-container-low": "hsl(var(--md-sys-color-surface-container-low) / <alpha-value>)",
                "m3-surface-container": "hsl(var(--md-sys-color-surface-container) / <alpha-value>)",
                "m3-surface-container-high": "hsl(var(--md-sys-color-surface-container-high) / <alpha-value>)",
                "m3-surface-container-highest": "hsl(var(--md-sys-color-surface-container-highest) / <alpha-value>)",
                "m3-inverse-surface": "hsl(var(--md-sys-color-inverse-surface) / <alpha-value>)",
                "m3-inverse-on-surface": "hsl(var(--md-sys-color-inverse-on-surface) / <alpha-value>)",
                "m3-inverse-primary": "hsl(var(--md-sys-color-inverse-primary) / <alpha-value>)",
            },
            transitionTimingFunction: {
                'm3-emphasized': 'cubic-bezier(0.2, 0.0, 0, 1.0)',
                'm3-emphasized-decelerate': 'cubic-bezier(0.05, 0.7, 0.1, 1.0)',
                'm3-emphasized-accelerate': 'cubic-bezier(0.3, 0.0, 0.8, 0.15)',
                'm3-standard': 'cubic-bezier(0.2, 0.0, 0, 1.0)',
                'm3-standard-decelerate': 'cubic-bezier(0.0, 0.0, 0.2, 1.0)',
                'm3-standard-accelerate': 'cubic-bezier(0.3, 0.0, 1.0, 1.0)',
            },
            transitionDuration: {
                'm3-short1': '50ms',
                'm3-short2': '100ms',
                'm3-short3': '150ms',
                'm3-short4': '200ms',
                'm3-medium1': '250ms',
                'm3-medium2': '300ms',
                'm3-medium3': '350ms',
                'm3-medium4': '400ms',
                'm3-long1': '450ms',
                'm3-long2': '500ms',
                'm3-long3': '550ms',
                'm3-long4': '600ms',
            },
            fontSize: {
                // Material Design 3 (M3) Canonical Typography Scale (Section 4)
                'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '400' }],
                'display-md': ['45px', { lineHeight: '52px', letterSpacing: '0px', fontWeight: '400' }],
                'display-sm': ['36px', { lineHeight: '44px', letterSpacing: '0px', fontWeight: '400' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0px', fontWeight: '400' }],
                'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '0px', fontWeight: '400' }],
                'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '0px', fontWeight: '400' }],
                'title-lg': ['22px', { lineHeight: '28px', letterSpacing: '0px', fontWeight: '400' }],
                'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.15px', fontWeight: '500' }],
                'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
                'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
                'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
                'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.4px', fontWeight: '400' }],
                'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
                'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
            },
            fontFamily: {
                sans: ["'Google Sans Flex'", "'Google Sans'", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Roboto", "Helvetica", "Arial", "sans-serif"],
                mono: ["'Google Sans Code'", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "'Liberation Mono'", "monospace"],
            },
            borderRadius: {
                "m3-none": "0px",
                "m3-xs": "4px",
                "m3-sm": "8px",
                "m3-md": "12px",
                "m3-lg": "16px",
                "m3-xl": "28px",
                "m3-full": "9999px",
                lg: "var(--radius)",
                md: "calc(var(--radius) - 4px)",
                sm: "calc(var(--radius) - 8px)",
            },

            boxShadow: {
                "xs": "0 1px 2px 0 rgba(0, 0, 0, 0.04)",
                "elevation-0": "none",
                "elevation-1": "0 1px 3px 0 rgba(0, 0, 0, 0.06), 0 1px 2px -1px rgba(0, 0, 0, 0.06)",
                "elevation-2": "0 3px 8px -1px rgba(0, 0, 0, 0.08), 0 1px 3px 0 rgba(0, 0, 0, 0.06)",
                "elevation-3": "0 6px 16px -2px rgba(0, 0, 0, 0.09), 0 2px 6px -1px rgba(0, 0, 0, 0.05)",
                "elevation-4": "0 12px 28px -4px rgba(0, 0, 0, 0.11), 0 4px 10px -2px rgba(0, 0, 0, 0.06)",
                "elevation-5": "0 20px 40px -6px rgba(0, 0, 0, 0.14), 0 8px 16px -3px rgba(0, 0, 0, 0.07)",
            },
            animation: {
                'fade-in': 'm3FadeIn 0.35s cubic-bezier(0.05, 0.7, 0.1, 1.0) forwards',
                'scale-in': 'm3ScaleIn 0.3s cubic-bezier(0.05, 0.7, 0.1, 1.0) forwards',
                'shared-axis-y': 'm3SharedAxisY 0.4s cubic-bezier(0.05, 0.7, 0.1, 1.0) forwards',
                'shared-axis-x': 'm3SharedAxisX 0.35s cubic-bezier(0.05, 0.7, 0.1, 1.0) forwards',
                'expand-container': 'm3ExpandContainer 0.45s cubic-bezier(0.2, 0, 0, 1) forwards',
                'page-enter': 'm3PageEnter 0.35s cubic-bezier(0.05, 0.7, 0.1, 1.0) forwards',
            },
            keyframes: {
                m3PageEnter: {
                    '0%': { opacity: '0', transform: 'translateY(10px) scale(0.992)' },
                    '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
                },
                m3FadeIn: {
                    '0%': { opacity: '0', transform: 'translateY(8px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                m3ScaleIn: {
                    '0%': { opacity: '0', transform: 'scale(0.94)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                m3SharedAxisY: {
                    '0%': { opacity: '0', transform: 'translateY(16px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                m3SharedAxisX: {
                    '0%': { opacity: '0', transform: 'translateX(12px)' },
                    '100%': { opacity: '1', transform: 'translateX(0)' },
                },
                m3ExpandContainer: {
                    '0%': { opacity: '0', transform: 'scaleY(0.95)', transformOrigin: 'top' },
                    '100%': { opacity: '1', transform: 'scaleY(1)', transformOrigin: 'top' },
                },
            },

        },
    },
    plugins: [],
} satisfies Config;